name: self-hosted integration test

on: workflow_dispatch

jobs:
  fargate:
    runs-on: [self-hosted, github-runner-service, 608616343410, us-east-1, fargate]
    steps:
      - run: ls -lah
      - name: git
        run: git --version
      - name: aws
        run: aws --version
      - name: show aws IAM role
        run: aws sts get-caller-identity
      - name: pipx confirm
        run: pipx --version
      - name: docker confirm
        run: docker --version

