name: self-hosted integration test

on: workflow_dispatch

jobs:
  fargate:
    runs-on: [self-hosted, nc-sb-fargate, foobar]
    steps:
      - run: ls -lah
      - name: git
        run: git --version
      - name: aws
        run: aws --version
      - name: show aws IAM role
        run: aws sts get-caller-identity
